# Libraries

In [1]:
import pandas as pd

# Data

In [2]:
pitch = pd.read_csv('../datasets/mlb_pitch_stats_19_21_cleaned.csv')
print(pitch.shape)
pitch.head()

(704, 95)

,player_id,last_name,first_name,year,age,ip,bf,ab,h,k%,...,cu_vb_avg,cu_brk_avg,cu_velo_range,2seam%,2seam_velo_avg,2seam_spin_avg,2seam_hb_avg,2seam_vb_avg,2seam_brk_avg,2seam_velo_range
0,425794,Wainwright,Adam,2021,40,196.1,784,725,157,21.6,...,-31.0,9.5,1.6,59.2,87.5,2297,-3.9,-25.0,14.3,2.7
1,425844,Greinke,Zack,2021,38,164.2,670,626,157,17.0,...,NaN,NaN,NaN,45.9,89.0,2225,-2.7,-18.6,16.7,1.3
2,429722,Santana,Ervin,2021,39,61.1,255,232,58,18.8,...,NaN,NaN,NaN,45.3,93.4,2179,-4.5,-17.2,15.0,1.3
3,433589,Petit,Yusmeiro,2021,37,72.1,290,273,63,12.4,...,-21.1,17.3,1.3,68.4,86.5,2134,-3.7,-18.8,18.3,2.1
4,445276,Jansen,Kenley,2021,34,61.2,250,210,33,29.6,...,-14.4,19.2,1.9,84.5,93.0,2578,2.7,-13.6,19.6,2.0

# Data Cleaning

### Nulls and dtypes

In [3]:
pitch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 704 entries, 0 to 703
Data columns (total 95 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         704 non-null    int64
 1   last_name         704 non-null    object
 2    first_name       704 non-null    object
 3   year              704 non-null    int64
 4   age               704 non-null    int64
 5   ip                704 non-null    float64
 6   bf                704 non-null    int64
 7   ab                704 non-null    int64
 8   h                 704 non-null    int64
 9   k%                704 non-null    float64
 10  bb%               704 non-null    float64
 11  ba                704 non-null    float64
 12  slg%              704 non-null    float64
 13  obp%              704 non-null    float64
 14  ops               704 non-null    float64
 15  earned_runs       704 non-null    int64
 16  era               704 non-null    float64
 17  qual_start        704 non-null    int64
 18  cg                704 non-null    int64
 19  xba               704 non-null    float64
 20  xslg              704 non-null    float64
 21  woba              704 non-null    float64
 22  xwoba             704 non-null    float64
 23  xobp              704 non-null    float64
 24  wobacon           704 non-null    float64
 25  xwobacon          704 non-null    float64
 26  bacon             704 non-null    float64
 27  xbacon            704 non-null    float64
 28  ev_avg            704 non-null    float64
 29  la_avg            704 non-null    float64
 30  sweet_spot%       704 non-null    float64
 31  barrel%           704 non-null    float64
 32  solid_contact%    704 non-null    float64
 33  poor_weak%        704 non-null    float64
 34  hard_hit%         704 non-null    float64
 35  z_swing%          704 non-null    float64
 36  z_swing_miss%     704 non-null    float64
 37  oz_swing%         704 non-null    float64
 38  oz_swing_miss%    704 non-null    float64
 39  oz_contact%       704 non-null    float64
 40  out_zone%         704 non-null    float64
 41  pitch_count       704 non-null    int64
 42  z_contact%        704 non-null    float64
 43  in_zone%          704 non-null    float64
 44  edge%             704 non-null    float64
 45  whiff%            704 non-null    float64
 46  swing%            704 non-null    float64
 47  gb%               704 non-null    float64
 48  fb%               704 non-null    float64
 49  ld%               704 non-null    float64
 50  po%               704 non-null    float64
 51  throws            704 non-null    object
 52  n_pitches         704 non-null    int64
 53  4seam%            678 non-null    float64
 54  4seam_velo_avg    678 non-null    float64
 55  4seam_spin_avg    678 non-null    float64
 56  4seam_hb_avg      678 non-null    float64
 57  4seam_vb_avg      678 non-null    float64
 58  4seam_brk_avg     678 non-null    float64
 59  4seam_velo_range  674 non-null    float64
 60  sl%               539 non-null    float64
 61  sl_velo_avg       539 non-null    float64
 62  sl_spin_avg       539 non-null    float64
 63  sl_hb_avg         539 non-null    float64
 64  sl_vb_avg         539 non-null    float64
 65  sl_brk_avg        539 non-null    float64
 66  sl_velo_range     536 non-null    float64
 67  ch%               570 non-null    float64
 68  ch_velo_avg       570 non-null    float64
 69  ch_spin_avg       570 non-null    float64
 70  ch_hb_avg         570 non-null    float64
 71  ch_vb_avg         570 non-null    float64
 72  ch_brk_avg        570 non-null    float64
 73  ch_velo_range     559 non-null    float64
 74  cb%               494 non-null    float64
 75  cb_velo_avg       494 non-null    float64
 76  cu_avg_spin       493 non-null    float64
 77  cb_hb_avg         494 non-null    float64
 78  cb_vb_avg         494 non-null    float64
 79  cb_brk_avg        494 non-null    float64
 80  cb_velo_range     489 non-null    float64
 81  cu%               231 non-null    float64
 82  cu_velo_avg       231 non-null    float64
 83  cu_spin_avg       231 non-null    float64
 84  cu_hb_avg         231 non-null    float64
 85  cu_vb_avg         231 non-null    float64
 86  cu_brk_avg        231 non-null    float64
 87  cu_velo_range     226 non-null    float64
 88  2seam%            704 non-null    float64
 89  2seam_velo_avg    704 non-null    float64
 90  2seam_spin_avg    704 non-null    int64
 91  2seam_hb_avg      704 non-null    float64
 92  2seam_vb_avg      704 non-null    float64
 93  2seam_brk_avg     704 non-null    float64
 94  2seam_velo_range  704 non-null    float64
dtypes: float64(80), int64(12), object(3)
memory usage: 522.6+ KB