# Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Data

In [5]:
pitch_data = pd.read_csv('../datasets/mlb_pitch_stats_19_20_21.csv')
pitch_data.drop(columns = ['Unnamed: 0'], inplace = True)
print(pitch_data.shape)
pitch_data.head()

(1072, 89)

,last_name,first_name,player_id,year,age,ip,bf,ab,h,k%,...,cb_brk,cb_velo_range,cu%,cu_velo,cu_spinrate,cu_hb,cu_vb,cu_brk,cu_velo_range,xops
0,Wainwright,Adam,425794,2021,40,196.1,784,725,157,21.6,...,22.3,1.6,22.2,85.0,2408.0,6.3,-31.0,9.5,1.6,0.681
1,Greinke,Zack,425844,2021,38,164.2,670,626,157,17.0,...,15.6,2.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.725
2,Santana,Ervin,429722,2021,39,61.1,255,232,58,18.8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.851
3,Petit,Yusmeiro,433589,2021,37,72.1,290,273,63,12.4,...,10.7,1.8,23.3,84.5,2133.0,-1.1,-21.1,17.3,1.3,0.722
4,Jansen,Kenley,445276,2021,34,61.2,250,210,33,29.6,...,0.0,0.0,57.1,92.5,2689.0,7.3,-14.4,19.2,1.9,0.570

# Modeling